## Imports

In [106]:
import pandas as pd
from datasets import load_dataset

In [107]:
hf_access_token = '<enter token here>'

## Load Data

#### Folk Tales

In [108]:
df_folk_tales = pd.DataFrame(columns=['trg', 'eng', 'tale', 'chapter'])

with open('data/kachalona.txt') as f: 
    text = f.read()
    text = text.split('\n-----\n\n')
    for idx, chapter in enumerate(text):
        chapter = chapter.split('\n')
        text_trg = chapter[::3]
        text_eng = chapter[1::3]

        n = len(text_trg)

        new_chapter_df = pd.DataFrame(zip(text_trg, text_eng, ['kachalona']*n, [idx+1]*n), columns=['trg', 'eng', 'tale', 'chapter'])
        df_folk_tales = pd.concat([df_folk_tales, new_chapter_df])

df_folk_tales

,trg,eng,tale,chapter
0,xabra m-mani hawex? xabra hawex m-xa ˤdae ˤqari.,From whom do we have a word? We have a word fr...,kachalona,1
1,belaw ˤqrağ ˤahra wele,Her house was in the outskirts of the country,kachalona,1
2,"xa brona ətwala, ˤrəwwa brona","She had one son, a grown boy",kachalona,1
3,ya brona heč la-godwa: xa šrae nixe brona wele,"This boy did nothing: he was a ""lamps extingui...",kachalona,1
4,kulla yoma yatəwwa reš tanura. kačal rešew m-q...,"Every day, he would sit upon the tanura (oven)...",kachalona,1
...,...,...,...,...
35,"""xa-kepa pel, reši ˤqatele!""","""Should one rock fall, my head will be split o...",kachalona,5
36,"nošew g-ləbbew maqule, haman dəqna-xwara tota ...","As he was talking to himself, the same dəqna-x...",kachalona,5
37,"məre baew: ""la-zdi jullox kullu šalxəttu, ˤore...","He said to him: ""Don't be afraid, take off all...",kachalona,5
38,"ma-t dəqna-xwara məre, kačalona axxa wədle","Whatever the dəqna-xwara said, kačalona did as...",kachalona,5
39,"ˤwəre g-ˤmoe nehra pərele, ˤmtele əl-xa-dašta ...","He went in to the water, crossed the river, a...",kachalona,5

In [109]:
df_malkammot = pd.read_csv('data/malkammot.csv')

df_malkammot['tale'] = 'malkammot'
df_malkammot['chapter'] = [1 if x < 20 else 2 for x in list(df_malkammot.index)]

df_folk_tales = pd.concat([df_folk_tales, df_malkammot])
df_malkammot.head()

,trg,eng,tale,chapter
0,"xa yoma b-yomawe, malkammot məre ba-əlha: “xa ...","One day in all the days, The Angel of Death sa...",malkammot,1
1,məre əlha: “ma abulet?”,G-d responded: “What do you want?”,malkammot,1
2,"malkammot məre: “abulen košen təxya, xazen šam...",The Angel of Death said: “I want to descend to...,malkammot,1
3,əlha məre: “ba-mayyox ile? ytuw tkox šulox wud...,G-d retorted: “What is it for you? Sit down in...,malkammot,1
4,malkammot lwele tqele əl-əlha,But the Angel of Death pleaded and begged to G-d,malkammot,1

In [110]:
print(f'Total sentences: {len(df_folk_tales)}')
df_folk_tales.to_csv('data/folk_tales.csv', index=False)

Total sentences: 166

#### FLORES-Plus Benchmark

In [111]:
flores = load_dataset('openlanguagedata/flores_plus')#, token = hf_access_token)

Using the latest cached version of the dataset since openlanguagedata/flores_plus couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/sam/.cache/huggingface/datasets/openlanguagedata___flores_plus/default/0.0.0/1c079b04e227e9646edd65ae6264339e5db97122 (last modified on Wed Apr 22 22:31:32 2026).

In [112]:
flores_eng = flores['dev'].filter(lambda ex: ex['iso_639_3'] == 'eng').shuffle()[:50]

In [113]:
df_flores = pd.DataFrame(flores_eng)[['id', 'text']]
df_flores.to_csv('data/flores.csv')
df_flores.head()

    id                                               text
0  829  An immigration checkpoint is usually the first...
1  730  This authentic community is located in Howe So...
2  654  Crime, and ill-will toward foreigners in gener...
3  372  Other scientists argue that these plants are v...
4  522  With fewer REMs per night, this state in which...

In [114]:
df_flores = pd.read_csv('data/flores_translated.csv')
df_flores.head()

,id,eng,trg
0,274,"Leslie Aun, a spokesperson for the Komen Found...","lezli +an, maqyantət +komen +faundešən, məra +..."
1,344,"Already reporting in English and Japanese, the...","xen xabar hiwala gaat ingəlisi inan +žapani, +..."
2,635,"In this resonance, magnetic field and radio wa...","g-d-ay +rezonans, +midan +mağnatisi inan +amwa..."
3,461,"For that reason, everything you see on the TV ...",bod-d-o mohona kud məndiğ xazetun +b-televizyo...
4,236,"""It's going to behave like water. It's transpa...",magon +moe šula b-oda. bas bahurtela magon +moe

#### Math Reasoning

In [115]:
# TODO

#### QA

In [116]:
# TODO